version: '3.8'
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=ChiBlePortfolio
      - POSTGRES_DB=portfolio
      - EMAIL_USER=phucchi12112004@gmail.com
      - EMAIL_PASSWORD=ChiBlePortfolio
      - JWT_SECRET_KEY=ChiBlePortfolio
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=ChiBlePortfolio
      - POSTGRES_DB=portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  # frontend:
  #   build:
  #     context: ./front-end
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - backend

volumes:
  pgdata: